apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-java-db-writer
  namespace: db-writer
  labels:
    app: poc-java-db-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-java-db-writer
  template:
    metadata:
      labels:
        app: poc-java-db-writer
    spec:
      containers:
        - name: poc-java-db-writer
          image: 512979937293.dkr.ecr.us-east-1.amazonaws.com/poc-java-db-writer:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://market-data-postgresql.database.svc.cluster.local:5432/marketdata
            - name: SPRING_DATASOURCE_USERNAME
              value: marketdata
            - name: SPRING_DATASOURCE_PASSWORD
              value: marketdata
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka.kafka.svc.cluster.local:9092
            - name: SPRING_LIQUIBASE_ENABLED
              value: "true"
            - name: SPRING_KAFKA_TOPIC
              value: "trade"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
