apiVersion: v1
kind: Service
metadata:
  name: poc-java-db-writer
  namespace: db-writer
spec:
  clusterIP: None       # ← headless, no ClusterIP assigned
  selector:
    app: poc-java-db-writer
  # no ports section needed – purely DNS
